/* MediSwift product catalog.
   Prices are indicative PHP estimates for display purposes — confirm
   exact pricing and stock via inquiry before fulfillment. */
window.MEDISWIFT_PRODUCTS = [
  {
    id: 'littmann-classic-iii',
    name: 'Littmann Classic III Stethoscope',
    category: 'Stethoscopes',
    icon: 'stethoscope',
    image: 'assets/images/products/littmann-classic-iii.jpg',
    price: 7450,
    tag: 'Best Seller',
    short: 'The gold-standard teaching stethoscope with tunable diaphragm for adult and pediatric use.',
    description: 'A dependable, versatile stethoscope trusted by nursing and medical students worldwide. Features a tunable diaphragm that lets you switch between low and high frequencies without flipping the chestpiece, a pediatric-side bell, and a durable next-generation tube that resists skin oil and alcohol.',
    features: ['Tunable diaphragm technology', 'Adult + pediatric chestpiece', 'Latex-free tubing', '5-year manufacturer warranty'],
  },
  {
    id: 'littmann-cardiology-iv',
    name: 'Littmann Cardiology IV Stethoscope',
    category: 'Stethoscopes',
    icon: 'stethoscope',
    price: 12900,
    tag: 'Premium',
    short: 'High-acoustic-sensitivity stethoscope for advanced cardiac and pulmonary assessment.',
    description: 'Built for clinical instructors, CHN supervisors, and students headed into critical care. Superior acoustics let you pick up subtle heart and lung sounds even in noisy ward environments.',
    features: ['Dual-lumen tubing for two-tube acoustics in one', 'Impedance-matched, ultra-sensitive diaphragm', 'Adjustable, anatomically-angled headset'],
  },
  {
    id: 'mediswift-pro-steth',
    name: 'MediSwift Professional Stethoscope',
    category: 'Stethoscopes',
    icon: 'stethoscope',
    price: 1850,
    tag: 'MediSwift Brand',
    short: 'Our in-house stethoscope — a reliable, budget-friendly staple for daily RLE and clinical duty.',
    description: 'Designed for nursing students who need dependable acoustics for daily hospital and community rounds without the premium price tag. Stainless-steel chestpiece with dual-head design and soft-seal eartips for all-day comfort.',
    features: ['Dual-head stainless steel chestpiece', 'Soft-seal comfort eartips', 'Available in 6 colorways', 'Includes name-tag spare parts kit'],
  },
  {
    id: 'mediswift-lite-steth',
    name: 'MediSwift Lightweight Dual-Head Stethoscope',
    category: 'Stethoscopes',
    icon: 'stethoscope',
    price: 950,
    tag: 'Student Value',
    short: 'The most affordable option for first-year nursing and CHN students on a tight budget.',
    description: 'A lightweight, no-frills stethoscope built to survive the demands of first-year skills lab and community immersion — without breaking a student budget.',
    features: ['Lightweight aluminum chestpiece', 'Non-chill diaphragm rim', 'Great for skills lab & RLE starter sets'],
  },
  {
    id: 'chn-bag-classic',
    name: 'Classic CHN Bag',
    category: 'CHN Bags',
    icon: 'bag',
    price: 1250,
    tag: null,
    short: 'The standard Community Health Nursing bag required for home visits and field practicum.',
    description: 'Water-resistant canvas CHN bag sized to DOH community health nursing standards, with a rigid base and multiple internal compartments for organizing instruments, supplies, and documentation during home visits.',
    features: ['DOH-standard sizing', 'Water-resistant canvas exterior', 'Rigid base, adjustable shoulder strap', 'Multiple internal compartments'],
  },
  {
    id: 'chn-bag-premium',
    name: 'Premium CHN Bag with Compartments',
    category: 'CHN Bags',
    icon: 'bag',
    price: 1650,
    tag: 'Popular',
    short: 'Reinforced CHN bag with dedicated pockets for BP apparatus, vials, and sterile supplies.',
    description: 'An upgraded CHN bag with padded, labeled compartments for a BP apparatus, thermometer, sterile gauze, vials, and documentation — keeping field kits organized during barangay health visits.',
    features: ['Padded equipment compartments', 'Insulated pocket for vials/vaccines', 'Reinforced stitching for daily field use', 'Reflective strip for evening visits'],
  },
  {
    id: 'nursing-kit-complete',
    name: 'Complete Nursing Kit Set',
    category: 'Nursing Kits & Tools',
    icon: 'first-aid',
    price: 3200,
    tag: 'Full Set',
    short: 'BP apparatus, stethoscope, penlight, bandage scissors, and tourniquet — all in one set.',
    description: 'Everything a nursing student needs for RLE and hospital duty in one bundle: aneroid BP apparatus, MediSwift dual-head stethoscope, LED penlight with pupil gauge, bandage scissors, and a reusable tourniquet, packed in a compact carrying case.',
    features: ['Aneroid sphygmomanometer', 'MediSwift stethoscope', 'Penlight, scissors, tourniquet', 'Compact zippered carrying case'],
  },
  {
    id: 'skills-lab-kit',
    name: 'Basic Skills Lab Kit',
    category: 'Nursing Kits & Tools',
    icon: 'clipboard',
    price: 1450,
    tag: null,
    short: 'The essentials for first-year Related Learning Experience (RLE) sessions.',
    description: 'A starter kit covering the basics needed for first-year skills laboratory sessions — vital signs tools and small instruments sized for a student locker.',
    features: ['Penlight + pupil gauge', 'Bandage scissors', 'Reusable tourniquet', 'Measuring tape'],
  },
  {
    id: 'bp-apparatus',
    name: 'Aneroid Sphygmomanometer (BP Apparatus)',
    category: 'Nursing Kits & Tools',
    icon: 'heart',
    price: 1100,
    tag: null,
    short: 'Calibrated manual BP apparatus with adult cuff, ideal for ward and community use.',
    description: 'A manual, calibrated aneroid sphygmomanometer with a standard adult cuff — reliable for both hospital duty and community health visits where power outlets aren’t guaranteed.',
    features: ['Calibrated aneroid gauge', 'Standard adult cuff (large cuff available)', 'Durable carrying case'],
  },
  {
    id: 'digital-thermometer',
    name: 'Digital Infrared Thermometer',
    category: 'Nursing Kits & Tools',
    icon: 'thermometer',
    price: 850,
    tag: null,
    short: 'Non-contact infrared thermometer for fast, hygienic vital signs monitoring.',
    description: 'A non-contact infrared thermometer for quick, hygienic temperature checks — useful for both clinical rotations and vaccination-day triage.',
    features: ['1-second readout', 'Fever alert indicator', 'Memory recall for last 20 readings'],
  },
  {
    id: 'penlight',
    name: 'Penlight with Pupil Gauge',
    category: 'Nursing Kits & Tools',
    icon: 'sparkle',
    price: 180,
    tag: 'Budget Pick',
    short: 'A pocket essential for neuro checks and general assessment.',
    description: 'Compact LED penlight with a printed pupil-size gauge, a must-have in every nursing student’s uniform pocket.',
    features: ['Bright white LED', 'Printed pupil gauge sleeve', 'Pocket clip'],
  },
  {
    id: 'ppe-starter-pack',
    name: 'PPE Starter Pack',
    category: 'PPE & Vaccination Supplies',
    icon: 'shield-plus',
    price: 450,
    tag: null,
    short: 'Surgical masks, face shield, gloves, and an isolation gown bundled for clinical duty.',
    description: 'A ready-to-go personal protective equipment bundle for hospital duty, community immersion, or vaccination-day volunteering.',
    features: ['10 surgical masks', 'Reusable face shield', 'Box of nitrile gloves', 'Disposable isolation gown'],
  },
];
